package com.kashi.grc.content.service;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The slug rule runs in three places — here, the front end's anchorFor(), and
 * the admin's live preview. They have to agree, because a heading anchor
 * generated by one and linked by another is a link that scrolls nowhere.
 */
class SlugServiceTest {

    private final SlugService service = new SlugService();

    @Test
    @DisplayName("accents are folded, not stripped")
    void foldsAccents() {
        // "scurit" would be the result of stripping rather than folding, and is
        // both wrong and hard to spot in a URL.
        assertThat(service.slugify("Sécurité des données")).isEqualTo("securite-des-donnees");
    }

    @Test
    @DisplayName("punctuation collapses to single hyphens with no leading or trailing ones")
    void collapsesPunctuation() {
        assertThat(service.slugify("  RBI's Level I — the 36 controls!  "))
                .isEqualTo("rbi-s-level-i-the-36-controls");
    }

    @Test
    @DisplayName("truncation does not leave a half word")
    void truncatesOnWordBoundary() {
        String slug = service.slugify(
                "a very long headline about incident reporting deadlines across every "
                + "Indian financial regulator and what each one actually requires in practice");
        assertThat(slug.length()).isLessThanOrEqualTo(80);
        assertThat(slug).doesNotEndWith("-");
    }

    @Test
    @DisplayName("collisions append -2, -3 and stay inside the length cap")
    void resolvesCollisions() {
        Set<String> taken = Set.of("soc-2-guide", "soc-2-guide-2");
        assertThat(service.unique("soc-2-guide", taken::contains)).isEqualTo("soc-2-guide-3");
    }

    @Test
    @DisplayName("a title that reduces to nothing still produces a usable slug")
    void handlesEmptyResult() {
        assertThat(service.slugify("!!!")).isEmpty();
        assertThat(service.unique("", s -> false)).isEqualTo("untitled");
    }
}
