package com.kashi.grc.content.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.text.Normalizer;
import java.util.Locale;
import java.util.function.Predicate;

/**
 * Slug generation and collision handling.
 *
 * ── ONE RULE, THREE PLACES ───────────────────────────────────────────────────
 * The same slugify rule runs here, in the front end's anchorFor() for heading
 * anchors, and in the admin's live slug preview. They must agree, because a
 * heading anchor generated by one and linked by another is a link that scrolls
 * nowhere. If you change this, change content-api.js too.
 *
 * 80 characters is the cap. Not because anything breaks past it, but because a
 * slug is read aloud in sales calls and pasted into Slack, and the tail of a
 * 200-character URL is noise carrying no ranking value.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SlugService {

    private static final int MAX_LENGTH = 80;

    /**
     * Lowercase, ASCII, alphanumeric and hyphen. Accents are folded rather than
     * stripped, so "Sécurité" becomes "securite" and not "scurit".
     */
    public String slugify(String input) {
        if (input == null || input.isBlank()) return "";
        String s = Normalizer.normalize(input, Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "")
                .toLowerCase(Locale.ROOT)
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("^-+|-+$", "");
        if (s.length() > MAX_LENGTH) {
            s = s.substring(0, MAX_LENGTH);
            // Don't leave a truncated word fragment hanging off a hyphen.
            int lastHyphen = s.lastIndexOf('-');
            if (lastHyphen > MAX_LENGTH / 2) s = s.substring(0, lastHyphen);
            s = s.replaceAll("-+$", "");
        }
        return s;
    }

    /**
     * Append -2, -3 ... until free.
     *
     * `taken` is passed in rather than injected so this stays usable for posts,
     * authors, categories and tags without four near-identical methods. The
     * suffix budget is kept inside the length cap, so a collision on an
     * 80-character slug does not produce an 82-character one.
     */
    public String unique(String base, Predicate<String> taken) {
        String slug = base.isBlank() ? "untitled" : base;
        if (!taken.test(slug)) return slug;

        for (int n = 2; n < 1000; n++) {
            String suffix = "-" + n;
            String trimmed = slug.length() + suffix.length() > MAX_LENGTH
                    ? slug.substring(0, MAX_LENGTH - suffix.length()).replaceAll("-+$", "")
                    : slug;
            String candidate = trimmed + suffix;
            if (!taken.test(candidate)) return candidate;
        }
        // A thousand collisions on one title means something is wrong upstream.
        throw new IllegalStateException("could not find a free slug for: " + base);
    }

    /** Heading anchors. Same rule, so the front end and the backend agree. */
    public String anchorFor(String headingText) {
        return slugify(headingText);
    }
}
