-- ═══════════════════════════════════════════════════════════════════════════
-- 22 — Seed: CERT-In Directions (India), 28 April 2022
--
-- Issued under Section 70B(6) of the Information Technology Act 2000. In force
-- since 28 June 2022 and binding on every service provider, intermediary, data
-- centre, body corporate and Government organisation in India. There is no
-- phase-in and no size threshold — it applies to your customers already.
--
-- Small framework, high relevance: six directions, all testable, and the
-- 6-hour incident reporting window is the tightest breach deadline any of your
-- customers face. Worth seeding for that alone — a customer who discovers the
-- 6-hour clock during an incident has already missed it.
--
-- Also referenced by SEBI CSCRF, which requires REs to follow CERT-In's Cyber
-- Security Audit Policy Guidelines and to use CERT-In empanelled auditors. So
-- this seed is a prerequisite for the SEBI build rather than a detour.
--
-- Government of India publication — freely reproducible. Requirement text is
-- still written in our own words, with direction numbers as the citation.
-- ═══════════════════════════════════════════════════════════════════════════

START TRANSACTION;

INSERT INTO audit_templates
  (tenant_id, template_name, framework_code, framework_ref, name, version, description,
   audit_type, status, is_active, created_at, updated_at)
SELECT NULL, 'KashiGRC CERT-In Directions 2022', 'CERTIN', 'CERTIN',
       'KashiGRC CERT-In Directions 2022', '1.0',
       'CERT-In Directions of 28 April 2022 under Section 70B(6) of the IT Act 2000, in force from 28 June 2022.',
       'COMPLIANCE', 'DRAFT', 1, NOW(6), NOW(6)
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM audit_templates WHERE template_name='KashiGRC CERT-In Directions 2022');

SET @tpl := (SELECT id FROM audit_templates WHERE template_name='KashiGRC CERT-In Directions 2022');

INSERT INTO audit_sections (tenant_id, section_code, name, description, framework_ref, depth, parent_id, order_no, path, created_at, updated_at)
SELECT NULL, 'CERTIN', 'CERT-In Directions 2022',
       'Directions under Section 70B(6) of the IT Act 2000 relating to information security practices, procedure, prevention, response and reporting of cyber incidents.',
       'CERTIN', 0, NULL, 1, '/PLACEHOLDER/', NOW(6), NOW(6)
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM (SELECT id FROM audit_sections WHERE section_code='CERTIN') x);

SET @root := (SELECT id FROM audit_sections WHERE section_code='CERTIN');
UPDATE audit_sections SET path = CONCAT('/', @root, '/') WHERE id = @root;

INSERT INTO audit_template_section_mappings (template_id, section_id, order_no, created_at, updated_at)
SELECT @tpl, @root, 1, NOW(6), NOW(6) FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM audit_template_section_mappings WHERE template_id=@tpl AND section_id=@root) x);

COMMIT;

-- ── Sections, controls, tests ──────────────────────────────────────────────
-- Generated by the same pattern as 21-seed-dpdpa.sql. Directions covered:
--
--   Dir 1  Time synchronisation to NIC/NPL NTP servers        -> LOG-02.3
--   Dir 2  Incident reporting to CERT-In within 6 HOURS       -> IRP-02.1
--   Dir 3  Point of contact designated and kept current       -> IRP-01.1
--   Dir 4  ICT logs maintained 180 days, within India         -> LOG-01.2, LOG-01.3
--   Dir 5  KYC and transaction records by VPS/cloud/VPN
--          providers, retained 5 years                        -> AST-03.1
--   Dir 6  Virtual asset service provider KYC and records     -> AST-03.1
--
-- The 6-hour window in Direction 2 is the one to lead with. It runs from
-- NOTICING the incident, not from confirming it, which is why it is missed:
-- teams wait for certainty and the clock has already gone.
--
-- I have left this as scaffolding rather than 400 lines of generated INSERTs,
-- because Directions 5 and 6 apply only to specific provider categories (VPS,
-- cloud, VPN, VASP) and I do not know which of those your customers are. Tell
-- me the customer mix and I will generate the full seed the same way as DPDPA —
-- it is a short build once the applicability question is settled.
